#!/usr/bin/env sh

set -euf

DOCKER_COMMAND=podman
export BUILDAH_FORMAT=docker

fullVersionNumber() {
    major=$(echo "$1" | cut -d '.' -f 1)
    minor=$(echo "$1" | cut -d '.' -f 2)
    patch=$(echo "$1" | cut -d '.' -f 3)
    patch=${patch:-0}
    echo "$major.$minor.$patch"
}

recommendedJavaVersion() {
    minor=$(echo "$1" | cut -d '.' -f 2)
    patch=$(echo "$1" | cut -d '.' -f 3)
    patch=${patch:-0}

    if [ "$minor" = "13-pre7" ] 2>/dev/null; then
        echo "8"
    elif [ "$minor" -lt 12 ] 2>/dev/null; then
        echo "8"
    elif [ "$minor" -lt 16 ] 2>/dev/null; then
        echo "11"
    elif [ "$minor" -eq 16 ] 2>/dev/null && [ "$patch" -ne 5 ] 2>/dev/null; then
        echo "11"
    elif [ "$minor" -eq 16 ] 2>/dev/null && [ "$patch" -eq 5 ] 2>/dev/null; then
        echo "16"
    else
        echo "17"
    fi
}

if ! command -v curl >/dev/null; then
    echo "curl not installed"
    exit 1
fi

if ! command -v jq >/dev/null; then
    echo "jq not installed"
    exit 2
fi

if ! command -v $DOCKER_COMMAND >/dev/null; then
    echo "$DOCKER_COMMAND not installed"
    exit 3
fi

version_groups=$(curl "https://papermc.io/api/v2/projects/paper/" 2>/dev/null |
    jq -c ".version_groups[]" |
    cut -d '"' -f 2)

latest_version=$(curl "https://papermc.io/api/v2/projects/paper/" 2>/dev/null |
    jq -c ".versions[-1]" |
    cut -d '"' -f 2)

for version_group in $version_groups; do
    versions=$(curl "https://papermc.io/api/v2/projects/paper/version_group/$version_group" 2>/dev/null |
        jq -c ".versions[]" |
        cut -d '"' -f 2)

    latest_group_version=""

    for version in $versions; do
        java_version=$(recommendedJavaVersion "$version")
        version_number=$(fullVersionNumber "$version")

        build=$(curl "https://papermc.io/api/v2/projects/paper/versions/$version" 2>/dev/null |
            jq -c '.builds[-1]')

        download_name=$(curl "https://papermc.io/api/v2/projects/paper/versions/$version/builds/$build" 2>/dev/null |
            jq -c '.downloads.application.name' |
            cut -d '"' -f 2)

        $DOCKER_COMMAND build -f ./slim/Dockerfile \
            --build-arg="JAVA_VERSION=$java_version" \
            --build-arg="PAPER_VERSION=$version" \
            --build-arg="PAPER_BUILD=$build" \
            --build-arg="PAPER_DOWNLOAD=$download_name" \
            -t "docker.io/robjdavey/minecraft-server:$version_number" \
            ./slim &&
            $DOCKER_COMMAND push "docker.io/robjdavey/minecraft-server:$version_number" &&
            latest_group_version=$version_number
    done

    $DOCKER_COMMAND tag "docker.io/robjdavey/minecraft-server:$latest_group_version" "docker.io/robjdavey/minecraft-server:$version_group"
    $DOCKER_COMMAND push "docker.io/robjdavey/minecraft-server:$version_group"
done

$DOCKER_COMMAND tag "docker.io/robjdavey/minecraft-server:$latest_version" "docker.io/robjdavey/minecraft-server:latest"
$DOCKER_COMMAND push "docker.io/robjdavey/minecraft-server:latest"
