services:
  minecraft:
    image: robjdavey/minecraft-server:$SERVER_VERSION-alpine
    restart: unless-stopped
    environment:
      - TZ=Europe/London
    ports:
      - 25565:25565
    volumes:
      - world:/app/world
      - world_nether:/app/world_nether
      - world_the_end:/app/world_the_end
volumes:
  world:
  world_nether:
  world_the_end:
